name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**.v"
      - "v.mod"
  pull_request:
    paths:
      - "**.v"
      - "v.mod"
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Format
        run: make fmt

      - name: Run tests
        run: make test
